// svelte/Widget.svelte
<script>
  import { onDestroy, onMount } from "svelte"
  import { mountWidget } from "../core/mountWidget.js"

  export let agentId
  export let baseUrl
  export let scriptSrc
  export let containerId

  let widget = null
  let mounted = false

  const unmount = () => {
    if (widget) {
      widget.unmount()
      widget = null
    }
  }

  onMount(() => {
    mounted = true
  })

  $: if (mounted) {
    unmount()
    if (agentId && baseUrl && scriptSrc) {
      widget = mountWidget({ agentId, baseUrl, scriptSrc, containerId })
    }
  }

  onDestroy(() => {
    unmount()
  })
</script>

// vue/Widget.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, watch } from "vue"
import { mountWidget, type MountedWidget } from "../core/mountWidget"

const props = defineProps<{
  agentId: string
  baseUrl: string
  scriptSrc: string
  containerId?: string
}>()

let widget: MountedWidget | null = null

const mount = () => {
  widget?.unmount()
  widget = mountWidget({
    agentId: props.agentId,
    baseUrl: props.baseUrl,
    scriptSrc: props.scriptSrc,
    containerId: props.containerId
  })
}

onMounted(mount)

watch(
  () => [props.agentId, props.baseUrl, props.scriptSrc, props.containerId],
  () => mount()
)

onBeforeUnmount(() => {
  widget?.unmount()
  widget = null
})
</script>
